version: "3.9"  # optional since v1.27.0
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
          - "8000:8000"    
  react-admin-ui:
    container_name: react-admin-ui
    build:
      context: react-admin-ui/.
      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  express-api:
    container_name: express-api
    build:
      context: express-api/.
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    command: npm start