# TODO - Security - only accept connections on a specific interface (eg, IP:Port)
# TODO - Security - mount volumes read only?

version: "3.0"  # optional since v1.27.0
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
          - "8000:8000"    
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal      
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  react-admin-ui:
    container_name: react-admin-ui
    build:
      context: react-admin-ui/.
      dockerfile: Dockerfile
    volumes:
      - './react-admin-ui:/app'
      - './react-admin-ui/node_modules:/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    command: npm start
  express-api:
    container_name: express-api
    build:
      context: express-api/.
      dockerfile: Dockerfile
    volumes:
      - './express-api:/app'
      - './express-api/node_modules:/app/node_modules'
    ports:
      - 3002:3000
      - 9229:9229
    command: npm start 