apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: express-api
  name: express-api
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3000
    - name: "9229"
      port: 9229
      targetPort: 9229
  selector:
    io.kompose.service: express-api
status:
  loadBalancer: {}
