apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: react-admin-ui
  name: react-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-admin-ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: react-admin-ui
    spec:
      containers:
        - args:
            - npm
            - start
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: WDS_SOCKET_PORT
              value: "0"
          image: rubegoldberg_react-admin-ui
          imagePullPolicy: Never
          name: react-admin-ui
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: react-admin-ui-claim0
            - mountPath: /app/node_modules
              name: react-admin-ui-claim1
      restartPolicy: Always
      volumes:
        - name: react-admin-ui-claim0
          persistentVolumeClaim:
            claimName: react-admin-ui-claim0
        - name: react-admin-ui-claim1
          persistentVolumeClaim:
            claimName: react-admin-ui-claim1
status: {}
